### ISSUE TITLE
Fast loading of neural network to Inf2

### ISSUE THREAD

**Issue by junoriosity** [aws-neuron/aws-neuron-samples#8] opened 2023-04-28 21:37 UTC
I managed to compile the [notebook in the samples](https://github.com/aws-neuron/aws-neuron-samples/blob/master/torch-neuronx/transformers-neuronx/inference/facebook-opt-13b-sampling.ipynb) to load an OPT model in `inf2` chips. :slight_smile: 

However, at one point I load the network and put it to neuron.

```
neuron_model = OPTForSampling.from_pretrained('./opt-13b-split', batch_size=2, tp_degree=2, amp='f16')
neuron_model.to_neuron()
```

and if I take a smaller model and increase the batch size, it can take ages (20 minutes or so).

Since I try to dockerize my network, can I somehow speed that up, such that my containers start up fast on Kubernetes?

**Comment by awsilya** [comment] 2023-05-03 18:49
@junoriosity thank you for your inquiry.

The delay is likely caused by model compilation.  A model needs to be compiled for running on Neuron.  For inferences a model can be precompiled and serialized as described here:  

https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuronx/transformers-neuronx/readme.html?highlight=transformers-neuronx#serialization-support

Unfortunately, we don't support OPT serialization yet but it will be available in future releases.

**Comment by junoriosity** [comment] 2023-05-03 20:36
@awsilya What was also a bit disappointing is that the actual performance was not better than running these OPT models on a G4 GPU ... sometimes even slower.

Do you have an idea, why is that?

**Comment by aws-taylor** [comment] 2024-05-22 15:42
Hello @junoriosity,

 There are numerous reasons why performance on an inf2 may be different than a GPU instance. Under the hood, they're fundamentally different architectures, with different strengths. I'd encourage you to take a look at the techniques described in https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/torch-neuronx/programming-guide/training/pytorch-neuron-debug.html to see if there are any obvious performance optimizations available.

**Comment by jeffhataws** [comment] 2024-07-01 21:16
Closing ticket as OPT is no longer supported. Please let us know if another model will work for you. Thanks!

**Comment by jeffhataws** [comment] 2024-07-01 21:16
Please also try release 2.18 for faster checkpoint loading feature: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/torch/transformers-neuronx/index.html?highlight=fast%20loading#release-0-10-0-21

**Closed by jeffhataws** 2024-07-01 21:16 UTC
